DROP DATABASE IF EXISTS 
CREATE DATABASE
USE 
CREATE TABLE 
INSERT INTO KK VALUES
UPDATE KK SET  ID='' WHERE ID=''
DELETE FROM KK WHERE 
SELECT*FROM
SELECT*FROM 
DELETE FROM KK WHERE
UPDATE KK SET ID WHERE ID
CREATE TABLE KK VALUES
USE
CREATE DATABASE
DROP DATABASE 