DROP DATABASE IF EXISTS LL;
CREATE DATABASE LL;
USE LL;
CREATE TABLE KK(ID INT,
NAME VARCHAR(3),
EAG VARCHAR(3),
eco VARCHAR(5));
INSERT INTO KK
VALUES('1','王二','18','67');
INSERT INTO KK 
VALUES('2','张三','22','87');

UPDATE KK SET EAG='19' WHERE ID='2';
set charset gbk;
SELECT*FROM KK;
